### ISSUE TITLE
Problems bundling gems that require gems in the stdlib

### ISSUE THREAD

**Issue by krig** [rubygems/rubygems#1400]
I am running `bundle package` to bundle all of the gems that my [Rails app][1] are using in order to package the app as a dependency-less `.rpm` for distribution. I've previously had the issue that if a gem that has been included in the stdlib is included in the `Gemfile`, bundler would crash with a nil dereference. To work around this, I strip the offending gems from the Gemfile before bundling (rdoc, rake and json).

However, recently one of the gems I depend on added [this line][2] where it calls `gem "json"` directly. With this line, gem doesn't find the json gem required in a Gemfile and fails, even though the json gem is available as part of the standard library.

It seems to me that `gem "json"` should always succeed since json is available, just not as a freestanding gem. The error I'm getting is [here][3]. I don't see why it's failing there since `json` is available.

[1]: https://github.com/ClusterLabs/hawk
[2]: https://github.com/webhippie/po_to_json/blob/master/lib/po_to_json.rb#L26
[3]: https://gist.github.com/krig/aa0bddad17b33099037f

**Comment by segiddins** [comment]
This is an issue with bundler, not rubygems, and I believe it's one we've addressed as of the 1.11 betas.

**Comment by krig** [comment]
@segiddins I wasn't sure exactly where the problem was. Yes, I've tried running with the patch for bundler (this one, right? https://github.com/bundler/bundler/commit/5f2d983fc909290599d04f4cd414334552add172). Unfortunately, that avoids the crash on null access in bundler, but bundler still fails since it can't bundle the gem, and `bundle package` ends up doing nothing. So the end result is just as bad for me.

But I'll open a bundler issue instead.

**Comment by krig** [comment]
Filed bundler/bundler#4131

**Comment by agis-** [comment]
This can be closed AFAICT :)
