### ISSUE TITLE
ERROR While executing gem - wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by timherby** [rubygems/rubygems#2224]
I'm having a problem installing gems in Ruby 2.5.0 using RVM.  Every time I try to install any gem, I get `While executing gem - wrong number of arguments (given 1, expected 0)`.  I have searched for answers elsewhere and in this project, but cannot seem to find anyone else with this issue.  This also does not happen with Ruby 2.3.6 in the same machine.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.1.11
```

Here is the full error:
```
tim$ gem install rake --backtrace
ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (given 1, expected 0)
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:46:in `require'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/installer.rb:103:in `initialize'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:93:in `new'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:93:in `block in install'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:84:in `each'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/request_set.rb:84:in `install'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/dependency_installer.rb:371:in `install'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/install_command.rb:180:in `install_gem'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/install_command.rb:194:in `block in install_gems'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/install_command.rb:190:in `each'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/install_command.rb:190:in `install_gems'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/commands/install_command.rb:146:in `execute'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/command.rb:305:in `invoke_with_build_args'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/command_manager.rb:167:in `process_args'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/command_manager.rb:137:in `run'
	/Users/tim/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/gem_runner.rb:54:in `run'
	/Users/tim/.rvm/rubies/ruby-2.5.0/bin/gem:21:in `<main>'
```

**Comment by segiddins** [comment]
Did you manually install RubyGems 2.1.11 ? The default with 2.5.0 should have been something like 2.7

**Comment by segiddins** [comment]
Aha! This is actually fixed in recent versions of rubygems, since they call `Kernel.gem` in `Kernel.require` directly. What's happening is that there's a `require` being called in a method that has a local variable called `gem`, which is shadowing the `Kernel` method. Updating rubygems should fix the issue!

**Comment by timherby** [comment]
Thanks for the super quick reply @segiddins!

That did the trick.  For the benefit of others, I ran the following to fix it:
```
rvm rubygems 2.7.6
```

And for reference, here is my upgrade to Ruby 2.5.0:
```
tim$ rvm reinstall 2.5.0
Removing /Users/tim/.rvm/src/ruby-2.5.0
Removing /Users/tim/.rvm/rubies/ruby-2.5.0
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.13/x86_64/ruby-2.5.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' already are up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/tim/.rvm/rubies/ruby-2.5.0, this may take a while depending on your cpu(s)...
ruby-2.5.0 - #downloading ruby-2.5.0, this may take a while depending on your connection...
ruby-2.5.0 - #extracting ruby-2.5.0 to /Users/tim/.rvm/src/ruby-2.5.0
ruby-2.5.0 - #extracted to /Users/tim/.rvm/src/ruby-2.5.0
ruby-2.5.0 - #configuring..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
ruby-2.5.0 - #post-configuration
ruby-2.5.0 - #compiling........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
ruby-2.5.0 - #installing.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Retrieving rubygems-2.1.11
Extracting rubygems-2.1.11 ...
Removing old Rubygems files...
Installing rubygems-2.1.11 for ruby-2.5.0.....

```
Looks like I just needed to force the upgrade of rubygems as well.

Thanks again for looking at this.

**Comment by Azuretyie** [comment]
I'm getting this.

**Comment by a2ikm** [comment]
I got the same error.
Reinstalling ruby 2.5.3 with rbenv didn't fix it.

So I updated `lib/rubygems/core_ext/kernel_require.rb` directly like [rubygems' commit](https://github.com/rubygems/rubygems/commit/439c4464890958fec17b3aa65b9d3a4dbdd3bf90), and updated rubygems with `gem update --system`.
