### ISSUE TITLE
prevent interactive prompts, for automated processes?

### ISSUE THREAD

**Issue by jrochkind** [rubygems/rubygems#2331]
There are potentially a couple places in rubygems that deliver an interactive y/n prompt. 

One:

```
$ sudo gem install bundler
Fetching: bundler-1.16.2.gem (100%)
bundler's executable "bundle" conflicts with /usr/local/bin/bundle
Overwrite the executable? [yN]
```

This is inconvenient for some automated orchestration/provisioning scripts we have, where that interactive prompt of course stops the script from proceeding. 

In this particular case, yeah we want to overwrite the executable, that's why the script was being run. 

I'm not sure if there are other cases that are more 'dangerous'. 

Would it be feasible to provide a command line option to `gem install` that avoids interactive prompts, or provides answers to them (or takes answers from an ENV variable?), or... something, to make it less problematic to automate `gem install` commands?

Thanks for any advice or feedback.

**Comment by jrochkind** [comment]
Here's where the interactive prompt is generated: https://github.com/rubygems/rubygems/blob/2606d580f3dd31b4cb12abf2719323010b59f6c3/lib/rubygems/installer.rb#L246-L258

This _might_ be the only interactive prompt right now, at least with `gem install`.  There aren't a lot of instances of use of the `ask_yes_no` method in source.

**Comment by bronzdoc** [comment]
@segiddins @duckinator what you think?

**Comment by MSP-Greg** [comment]
I have to check further, but I've got a script function used in Appveyor that installs/updates gems, and both use `-q` and `-f`, and no prompts are required.  I know the rake bin stub is overwritten, but I don't think I've installed/updated bundler, which may have more...

**Comment by jrochkind** [comment]
Looking at `-f`, indeed it does that, but also skips `ensure_required_ruby_version_met`, `ensure_required_rubygems_version_met`, and `ensure_dependencies_met`. Possibly more. Some of those don't seem like things one would want to skip, I think? Not sure.

**Comment by MSP-Greg** [comment]
@jrochkind

Thank you for pointing that out.  Almost all of what I use it for is updating what Ruby considers 'bundled' gems (minitest, rake, test-unit, etc).  But I recently used it for `rspec`, and it did install all the dependencies.  Also, I don't think I've used it with anything older that Ruby 2.0...

> Some of those don't seem like things one would want to skip, I think?

I would certainly agree.

As to dangerous, a gem could erase all sorts of things on `require`, so I think the CI issues of being able to remove UI/interactive prompts overrides any 'dangerous' issues.

Greg

**Comment by duckinator** [comment]
Using `--force` to get this behavior feels very risky, to me 

I'd personally recommend a flag explicitly meant for this purpose, such as what is offered by dnf (`-y`/`--assumeyes`) and apt-get (`-y`/`--assume-yes`).

If we add this to RubyGems and/or bundler, I'd suggest `--assume-yes` (with the hyphen in the middle) to match the formatting of other flags.

**Comment by jrochkind** [comment]
@MSP-Greg 

Yeah, I didn't _think_ it skipped installing dependencies in my actual obseration, but it _does_ skip one invocation of a method named `ensure_dependencies_met`. I can't explain it. maybe that method doesn't do what one would expect, or maybe it's actually doing it duplicated work somewhere. 

https://github.com/rubygems/rubygems/blob/2606d580f3dd31b4cb12abf2719323010b59f6c3/lib/rubygems/installer.rb#L881-L885

Got me, but maybe does not matter for this issue.

**Comment by MSP-Greg** [comment]
Constraining this just to the 'overwrite executable' questions, is this as simple as:

```diff
# Patch by MSP-Greg
# Add Install/Update option to remove prompts for executables
diff --git a/bundler b/bundler
@@ -203,6 +203,11 @@ module Gem::InstallUpdateOptions
       options[:suggest_alternate] = v
     end
 
+    add_option(:"Install/Update", '--assume-yes',
+               'Always answer yes to questions, useful for script') do |v,o|
+      options[:assume_yes] = true
+    end
+
   end
 
   ##
diff --git a/lib/rubygems/installer.rb b/lib/rubygems/installer.rb
index 3b13d233..77426ec5 100644
--- a/lib/rubygems/installer.rb
+++ b/lib/rubygems/installer.rb
@@ -241,6 +241,11 @@ class Gem::Installer
     # somebody has written to RubyGems' directory, overwrite, too bad
     return if Gem.default_bindir != @bin_dir and not ruby_executable
 
+    if options[:assume_yes]
+      say "Overwriting executable"
+      return true
+    end
+
     question = "#{spec.name}'s executable \"#{filename}\" conflicts with ".dup
 
     if ruby_executable then
```

**Comment by segiddins** [comment]
https://github.com/rubygems/rubygems/blob/master/lib/rubygems/user_interaction.rb#L250

Looks like we're already short-circuiting when not running in a TTY ?

**Comment by MSP-Greg** [comment]
I believe that returns `default`, which is `false` in this case.  We need `true` returned, so the bin stubs/executables are overwritten...

**Comment by MSP-Greg** [comment]
1. Tests - adding a new option to the test for install_update_options.rb is simple.  I haven't thought about how to test the change in installer.rb.

2. Change `--assume-yes`?  Maybe --overwrite-exec'?  If you uninstall a dependency, there are a few questions that I think should not be ignored (or answered true).  I think this option should only apply to install/update, which is why I put it there...

**Comment by MSP-Greg** [comment]
See PR #2338

**Comment by hsbt** [comment]
See my comment: https://github.com/rubygems/rubygems/pull/2338#issuecomment-401377608

This is caused by inconsistency behavior between the installer of Ruby and RubyGems. We should fix the behavior of installer of Ruby.

**Comment by hsbt** [comment]
@MSP-Greg Bundler is installed from RubyGems updater used by `gem update --system` as default gems. You need to learn its mechanism at least.

**Comment by jrochkind** [comment]
This is still annoying me. 

As another example, I want to be able to `gem uninstall --all` to uninstall all gems. 

With that command as it is, I get prompts `If you remove this gem, these dependencies will not be met. Continue with Uninstall?`. 

Okay, so I try `gem uninstall --all --force`. That eliminates the "these dependencies will not be met" prompts, but I still get "Remove executables... in addition to this gem?" prompts. 

As I have lots of gems installed I get a _lot_ of these prompts. 

Shouldn't there be a way for me to uninstall all gems in one command without having to type a key a hundred times to confirm?

**Comment by hsbt** [comment]
This issue was fixed at Ruby 2.6: https://github.com/ruby/ruby/commit/a94332819463589fe4537cc62beb41a0ee354cf3

**Comment by hsbt** [comment]
@jrochkind Your last proposal is different from the first report. Can you file it with another issue?
