### ISSUE TITLE
--regenerate-binstubs argument to setup.rb does not respect --destdir

### ISSUE THREAD

**Issue by Roguelazer** [rubygems/rubygems#2370]
I'm packing a new versions of rubygems for a distribution and it appears that some time between the last time I did this (2.6.14) and now (2.7.7), the `--regenerate-binstubs` argument became the default; this argument does not respect the `--destdir` argument and always attempts to write into the actual prefix. This makes it difficult to package rubygems into an RPM. Packaging works correctly if `--no-regenerate-binstubs` is passed, but I feel like I ought to be regenerating binstubs.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
I believe the `--destdir` argument is only meant to control where _rubygems itself_ gets installed, and not where the underlying gems get put?

**Comment by Roguelazer** [comment]
Yes, this is an issue occuring while installing rubygems itself with `/path/to/ruby setup.rb --prefix=/path/to/prefix --destdir=$HOME/rpmbuild/BUILDROOT/blah/`

**Comment by tjouan** [comment]
> I'm packing a new versions of rubygems for a distribution and it appears that some time between the last time I did this (2.6.14) and now (2.7.7), the --regenerate-binstubs argument became the default; this argument does not respect the --destdir argument and always attempts to write into the actual prefix.

  It was added in v2.7.0 (909b5fb81), but at the time the option itself was
dead code: using `--no-regenerate-binstubs` had no effect, and the related code
was always executed. Also if I recall correctly, there was another issue
breaking `--destdir` option when `Gem::USE_BUNDLER_FOR_GEMDEPS` was `true` and
it was fixed in v2.7.1 (not 100 % sure, but 5d5f0c39 and 76945185 might be
related).

  In the original patch I used, I had changed the default value to `false`
because I think this should be the default behavior. But since this feature was
already released, in the end I only submitted a patch to make
`--no-regenerate-binstubs` work: #2099. So starting with v2.7.3, we *must*
specify `--no-regenerate-binstubs` when using `--destdir`. Alternatively,
patching `Gem::USE_BUNDLER_FOR_GEMDEPS` to be `false` allows using `--destdir`
alone if I'm correct (which would be done when building a package).

  Then in v2.7.5 you can just set `DONT_USE_BUNDLER_FOR_GEMDEPS=yes`
environment variable instead of patching, and again `--destdir` might work
without `--no-regenerate-binstubs`.

  I attempted to fix this issue here: #2106. But attempting to support Windows
was too difficult for me (lack of knowledge and no direct access to this
platform), I didn't like the code I wrote for Windows support and closed the PR.
There are a few questions in the last comment but I received no feedback.

  Later, you reported the same issue: #2134, where I suggested some patches,
but intended only for your port, not upstream (knowing they didn't support
Windows). I failed to participate at the time, which resulted on changes in
RubyGems based on my (incorrect) patches: #2169, #2178 (last one fix the first
one).


> This makes it difficult to package rubygems into an RPM.

  I agree, in my opinion this feature should not have been enabled by default,
or maybe wait for RubyGems 3. But I think it might be too late now.

  However, does setting `DONT_USE_BUNDLER_FOR_GEMDEPS=yes` and not using
`--[no-]regenerate-binstubs` at all solves your issue? Because if you package
into RPM, I guess bundler would be a separate package
anyway.


> Packaging works correctly if --no-regenerate-binstubs is passed, but I feel like I ought to be regenerating binstubs.

  I don't really know which use case needs "regenerating binstubs", but when
packaging, I don't think we want/need this. I found my original patch, and
realize that I removed some context before submitting the one that got merged:
```
commit a430e12d91c9207b2ae1c8e2586a68e6a4ff19ef
Author: Thibault Jouan
Date:   Wed Nov 8 20:32:41 2017 +0000

    Fix setup command --regenerate-binstubs option flag

      The new --[no-]regenerate-binstubs option should probably not be
    enabled by default, as we cannot install any gems before installing
    rubygems itself. In most case the setup command will not be used by end
    users, but by maintainers of OS or distributions when building a
    "package" for rubygems. Developers and some users may need to run this
    command when working on the code or for specific install methods, it
    might be more safe to require explicit --regenerate-binstubs usage if
    needed.
[…]
```

**Comment by tjouan** [comment]
> I believe the --destdir argument is only meant to control where rubygems itself gets installed, and not where the underlying gems get put?

  I think that people who use this option expect that *nothing* outside the
given directory will be created, modified or removed. When packaging,
everything must happen in a single "staging" directory, which in a way is
equivalent to the file system root (`/`) for this package.

  If something happens outside this directory, then the package would probably
be broken, and some build system will detect the issue and fail immediately.

**Comment by Roguelazer** [comment]
@tjouan thanks for the comprehensive reply; I am already setting `DONT_USE_BUNDLER_FOR_GEMDEPS` to avoid installing bundler; however, with `DONT_USE_BUNDLER_FOR_GEMDEPS`, install still fails without `--no-regenerate-binstubs`

```
Installing gem executable
install -c -m 755 /tmp/gem.1978 /home/build/rpmbuild/BUILDROOT/ruby25-2.5.1-1.el6.x86_64/opt/ruby2.5/bin/gem
rm /tmp/gem.1978
RubyGems 2.7.7 installed
Regenerating binstubs
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems [] >= 0
error: Bad exit status from /var/tmp/rpm-tmp.RjCkS9 (%install)
```

It's frustrating that every time I build a new version of rubygems it seems to be broken in some new novel way. :-(

**Comment by segiddins** [comment]
> When packaging,
everything must happen in a single "staging" directory, which in a way is
equivalent to the file system root (/) for this package.

In that case, it seems like explicitly _not_ regenerating binstubs is what you want?

**Comment by tjouan** [comment]
> Could the default be changed to `--regenerate_binstubs` instead of
> `--no-regenerate_binstubs` for RubyGems 3 maybe?

Or RubyGems 4 if it's too late for 3 (#2191).

**Comment by segiddins** [comment]
The idea was to regenerate them so changes/improvements in the bin stub contents would be rolled out to users
