### ISSUE TITLE
Bundler 2.2.0 fails on JRuby 9.2 on Windows

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#4129]
See https://github.com/ruby/setup-ruby/runs/1542347124
Happens with both JRuby 9.2.14.0 and 9.2.13.0 on both windows-2016/2019 in GitHub Actions.

I'm not sure if it's an issue of JRuby or Bundler (or both), but AFAIK it did not happen with Bundler 2.1.4, so I guessed it's a Bundler issue.
cc @headius 

```
  C:\windows\system32\cmd.exe /D /S /C "D:\jruby-9.2.14.0\bin\gem.bat install bundler -v "~> 2" --no-document"
  Successfully installed bundler-2.2.0
  1 gem installed
  Took  21.69 seconds
```
```
 C:\windows\system32\cmd.exe /D /S /C "D:\jruby-9.2.14.0\bin\bundle.bat config --local path vendor/bundle"
  C:\windows\system32\cmd.exe /D /S /C "D:\jruby-9.2.14.0\bin\bundle.bat lock"
  D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:162: warning: Process#getrlimit not supported on this platform
```

  # Error Report
  
  ## Questions
  
  - **What did you do?**
  
    I ran the command `D:\jruby-9.2.14.0\bin\bundle lock`

  ## Backtrace
  
  ```
  NoMethodError: undefined method `first' for 9223372036854775807:Integer
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:162:in `<class:Persistent>'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:144:in `<main>'
    org/jruby/RubyKernel.java:974:in `require'
    org/jruby/RubyKernel.java:1002:in `require_relative'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendored_persistent.rb:11:in `<main>'
    org/jruby/RubyKernel.java:974:in `require'
    org/jruby/RubyKernel.java:1002:in `require_relative'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/fetcher.rb:3:in `<main>'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli/lock.rb:21:in `run'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli.rb:684:in `lock'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/exe/bundle:49:in `block in <main>'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
    D:/jruby-9.2.14.0/lib/ruby/gems/shared/gems/bundler-2.2.0/exe/bundle:37:in `<main>'
    org/jruby/RubyKernel.java:1009:in `load'
    D:\jruby-9.2.14.0\bin\bundle:23:in `<main>'
  ```
  
  ## Environment
  
  ```
  Bundler       2.2.0
    Platforms   ruby, universal-java-1.8
  Ruby          2.5.7p0 (2020-12-08 revision 67816) [java]
    Full Path   D:/jruby-9.2.14.0/bin/jruby.exe
    Config Dir  D:/jruby-9.2.14.0/etc
  RubyGems      3.0.6
    Gem Home    D:/jruby-9.2.14.0/lib/ruby/gems/shared
    Gem Path    C:\Users\runneradmin/.gem/jruby/2.5.0;D:/jruby-9.2.14.0/lib/ruby/gems/shared
    User Home   C:\Users\runneradmin
    User Path   C:\Users\runneradmin/.gem/jruby/2.5.0
    Bin Dir     D:/jruby-9.2.14.0/bin
  OpenSSL       
    Compiled    JRuby-OpenSSL 0.10.5
    Loaded      JRuby-OpenSSL 0.10.5
    Cert File   C:\Program Files\Java\jdk8u275-b01\jre/lib/security/cacerts
    Cert Dir    C:\Program Files\Java\jdk8u275-b01\jre/lib/security
  Tools         
    Git         2.29.2.windows.2
    RVM         not installed
    rbenv       not installed
    chruby      not installed
  ```
  
  ## Bundler Build Metadata
  
  ```
  Built At          2020-12-10
  Git SHA           d3628e5019
  Released Version  true
  ```
  
  ## Bundler settings
  
  ```
  path
    Set for your local app (D:/a/setup-ruby/setup-ruby/.bundle/config): "vendor/bundle"
  ```
  
  ## Gemfile
  
  ### Gemfile
  
  ```ruby
  # Used for testing
  source 'https://rubygems.org'
  
  gem "rake"
  gem "path"
  gem "json", "2.2.0"
  ```
  
  ### Gemfile.lock
  
  ```
  <No D:/a/setup-ruby/setup-ruby/Gemfile.lock found>
  ```

**Comment by headius** [comment]
This was caused by updating the vendored version of net-http-persistent, which pulled in this commit: 6532dbecf36d1f24dab1f2143afd171e0b7699eb

The old use of `Gem.win_platform?` was likely never returning true on JRuby since it uses `RUBY_PLATFORM` instead of the RbConfig `host_os` value. With the change to checking for `RLIMIT_NOFILE` the condition now is true on JRuby and exposes a bug in our implementation of `Process.getrlimit`.

Specifically, the JRuby logic for `getrlimit` on Windows or when running without native library support is broken up through 9.2.14.0 because it only returns a single value rather than an array of min/max values. That issue was fixed in jruby/jruby#6383 as part of work to better support execution without native library support, but those fixes have not been backported to the 9.2 line.

There are no specs for Windows behavior of `getrlimit` because CRuby does not define `getrlimit` or the related methods when the related identifiers are not defined.

So the proper fix in JRuby would seem to be to mark `getrlimit` as unimplemented and not define the related constants when we are on Windows or unable to support them, which would prevent net-http-persistent from even attempting to call this code.

In the short term, a JRuby check could be added to net-http-persistent, since that library and this vendored version of it will now simply not work on Windows or non-native JRuby environments. Even if we were to patch this for an as-yet-unplanned 9.2.15.0, it would still affect every prior JRuby version.

I will file an issue for JRuby to do a better fix when `getrlimit` can't be supported.

**Comment by deivid-rodriguez** [comment]
Thanks for figuring this out @headius!

Is there any thing we can do on our side (or net-http-persistent's) to alleviate the issue?

**Comment by eregon** [comment]
Another issue reported for this: https://github.com/ruby/setup-ruby/issues/129
A JRuby 9.2.14.1 or 9.2.15.0 release seems the best way to address this.

**Comment by slonopotamus** [comment]
I wonder how it passed through rubygems CI. It doesn't test against JRuby on Windows?

As I understand, there will soon be a new release of Ruby with a fix. Are any actions going to be made on rubygems side to fix Bundler on current JRuby releases?

**Comment by deivid-rodriguez** [comment]
> I wonder how it passed through rubygems CI. It doesn't test against JRuby on Windows?

Not at the moment, we have some jruby testing in place, but not on Windows. Even if we had it, bugs still happen, although I agree this kind of thing should've been very easily caught by CI.

> As I understand, there will soon be a new release of Ruby with a fix. Are any actions going to be made on rubygems side to fix Bundler on current JRuby releases?

If you read just a bit up, you'll find that I have just asked about this.

**Comment by deivid-rodriguez** [comment]
I added a naive workaround at #4138.

**Comment by headius** [comment]
> A JRuby 9.2.14.1 or 9.2.15.0 release seems the best way to address this.

The proper JRuby fix will be in the next release, but no releases will happen until January.

Even then, that release will do nothing to help users on JRuby 9.2.14.0 and earlier, and there are many production JRuby apps out there that will break the next time Bundler is updated.

Without a workaround, it will be impossible to use latest Bundler on **any currently released version of JRuby**. That does not seem like an acceptable situation to me.

The fix proposed by @deivid-rodriguez will work just fine, so I hope it will get a quick release.

I am standing by to help get more JRuby jobs into the Bundler CI, so that this sort of catastrophic breakage does not happen in the future.

**Comment by headius** [comment]
The JRuby fixes have been merged and will be in 9.2.15.0 or 9.3, whichever comes first.

**Comment by deivid-rodriguez** [comment]
Great, bundler 2.2.1 is out too!

**Comment by slonopotamus** [comment]
I've analyzed current situation a bit more to understand why we ended where we are:

- Bundler doesn't run tests on JRuby + Windows
- Bundler vendored net-http-persistent that doesn't run CI on Windows
- This vendoring happened between 2.2.0.rc.1 and 2.2.0
- net-http-persistent uses Hoe that doesn't have CI *at all*

Making conclusion from all of this is left as an excercise to the reader.

**Comment by deivid-rodriguez** [comment]
> This vendoring happened between 2.2.0.rc.1 and 2.2.0

If by this you mean that rc versions and final versions should only differ in bug fixes, you are right, and that's my fault. The rc name was definitely wrong. Anyways, virtually nobody installs pre-releases of bundler. I tried to use them to get some extra feedback before final releases, and I even "cheated" by calling them "rc", but it doesn't work so I'm going to propose to the team to stop pre-releases in favour of releasing more final versions.

**Comment by slonopotamus** [comment]
> Anyways, virtually nobody installs pre-releases of bundler.

**I** tested rc.1 during https://github.com/rubygems/rubygems/issues/3256 and it worked perfectly. This is exactly the kind of feedback you've looked for "rc" releases.

**Comment by deivid-rodriguez** [comment]
Not really, you installed it because I told you to. Had I suspected the fix was in master, not on 2.2.0.rc.1, I would've told you to install the master version.

The kind of feedback I was looking for is people opting into testing out rcs and discovering issues, but in both bundler 2.1 and bundler 2.2 that has been really weird.

**Comment by headius** [comment]
@deivid-rodriguez I feel your pain... people rarely test RCs, which is why we also stopped releasing them even for gigantic releases. I guess the safest assumption for all folks involve is that "dot zero" releases are basically the only RCs people will test, and we should just be prepared to put out a "dot one" soon after.

Thanks again for the quick flip on this.

**Comment by deivid-rodriguez** [comment]
Yay, `.0` is the new `rc` :)
