### ISSUE TITLE
bundle lock --add-platform no longer updates native gems on Bundler 2.5.12

### ISSUE THREAD

**Issue by stanhu** [rubygems/rubygems#7798]
### Describe the problem as clearly as you can

On a `Gemfile.lock` with only `ruby` in the `PLATFORMS` gem, `bundle lock --add-platform x86_64-linux` no longer updates `Gemfile.lock` with the platform-specific gems.

### Did you try upgrading rubygems & bundler?

Yes.

#### `Gemfile`

```ruby
source 'https://rubygems.org'

gem 'faraday'
gem 'nokogiri'
```

##### `Gemfile.lock`

```
GEM
  remote: https://rubygems.org/
  specs:
    faraday (2.9.2)
      faraday-net_http (>= 2.0, < 3.2)
    faraday-net_http (3.1.0)
      net-http
    mini_portile2 (2.8.7)
    net-http (0.4.1)
      uri
    nokogiri (1.16.6)
      mini_portile2 (~> 2.8.2)
      racc (~> 1.4)
    racc (1.8.0)
    uri (0.13.0)

PLATFORMS
  ruby

DEPENDENCIES
  faraday
  nokogiri

BUNDLED WITH
   2.5.12
```

### Which command did you run?

With the files above in `/tmp/test`, I ran:

```shell
docker run -v /tmp/test:/test -it ruby:3.2 bash
cd /test
cp Gemfile.lock Gemfile.lock.orig
gem install bundler -v 2.5.11
bundle --version # Check that this is 2.5.11
bundle lock --add-platform x86_64-linux
```

This properly updates `Gemfile.lock`:

```diff
root@8590139b4f72:/test# diff Gemfile.lock.orig Gemfile.lock
13a14,15
>     nokogiri (1.16.6-x86_64-linux)
>       racc (~> 1.4)
18a21
>   x86_64-linux
25c28
<    2.5.12
---
>    2.4.19
```

WIth Bundler v2.5.12, the same `bundle lock --add-platform x86_64-linux` does nothing.

### What were you expecting to happen?

`bundle lock --add-platform x86_64-linux` should update `Gemfile.lock` with x86 native gems.

### What actually happened?

No change.

A `git bisect` revealed that https://github.com/rubygems/rubygems/pull/7731 introduced the issue. 

Commenting out the line below resolves the issue: https://github.com/rubygems/rubygems/blob/d024794af7a68031a91c7c8fa37a87d699d53ca9/bundler/lib/bundler/definition.rb#L631

**Comment by deivid-rodriguez** [comment]
How about with 2.5.14? That change indeed caused a regression but it was fixed. It may be the same culprit.

**Comment by stanhu** [comment]
Oh, sorry, it looks like 2.5.14 did fix it. I had only tested 2.5.13.

**Comment by deivid-rodriguez** [comment]
No problem!

**Comment by stanhu** [comment]
@deivid-rodriguez Actually, I'm still seeing this problem with 2.5.14 with a different `Gemfile.lock`. The reproduction step above doesn't have any issue with 2.5.14 now, but I still see the issue this way?

```
docker run -it ruby:3.2 bash
cd /tmp
git clone --depth 1 -b renovate-gems/testing-gems https://gitlab.com/gitlab-renovate-forks/gitlab.git
cd gitlab
gem install bundler -v 2.5.14 # If I downgrade this to 2.5.11, it works fine
bundle lock --add-platform x86_64-linux
git diff
```

Commenting out the line below resolves the issue: https://github.com/rubygems/rubygems/blob/d024794af7a68031a91c7c8fa37a87d699d53ca9/bundler/lib/bundler/definition.rb#L631

**Comment by deivid-rodriguez** [comment]
Oh, I see. Let me fix it!

**Comment by deivid-rodriguez** [comment]
#7803 should fix this 👍.

**Comment by stanhu** [comment]
@deivid-rodriguez Thanks so much!
