### ISSUE TITLE
rake release step fails in release-please github action

### ISSUE THREAD

**Issue by phoet** [rubygems/rubygems#8493]
### Describe the problem as clearly as you can

For the valid_email2 gem we have release-please set up, so that all maintainers can cut a release. I've noticed that just recently the release-task has stopped working. It stops at `bundle exec rake release` and complains about gem versions ie: 

> bundler: failed to load command: rake (/home/runner/work/valid_email2/valid_email2/vendor/bundle/ruby/3.3.0/bin/rake)
> /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated uri 0.13.0, but your Gemfile requires uri 1.0.2. Since uri is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports uri as a default gem. (Gem::LoadError)

### Post steps to reproduce the problem

see failed action here https://github.com/micke/valid_email2/actions/runs/13325375394/job/37217370456

### Which command did you run?

i've tried to reproduce it locally with `bundle exec rake release` but since i dont have the authentication-codes, i dont know if the steps fail after logging in to rubygems.

things i've tried

- pinning the gem-version: works, but brings up the next gem that is not activated correctly
- invalidting the bundler cache: i set the version to 1 in order to get a clean cache, nothing changed
- using a different ruby-version: just different gem conflicts

**Comment by deivid-rodriguez** [comment]
Please verify if this works using `rubygems: latest` and `bundler: latest`.

**Comment by deivid-rodriguez** [comment]
I'm pretty sure adding `rubygems: latest` as a `ruby/setup-ruby` action input in your release workflow will fix this.

The `uri` conflict in particular was probably fixed by https://github.com/rubygems/rubygems/pull/7386, released as RubyGems 3.5.6, and the `securerandom` one was fixed by https://github.com/rubygems/rubygems/pull/7960, released as Rubygems 3.6.0.

I don't think your workflows are using a RubyGems version that includes these fixes, hence the issue.

I'm going to close since I'm pretty sure this is fixed in the latest RubyGems version, but if I'm wrong, please do reopen!

**Comment by phoet** [comment]
@deivid-rodriguez sorry for highjacking this issue, but since it's the same task, maybe it's something you also know.

with `rubygems: latest` the task does not fail with gem dependency issues, but after running the tests, the task fails because it tries to push the same tag twice:

```
Finished in 2.29 seconds (files took 0.50535 seconds to load)
108 examples, 0 failures
valid_email2 7.0.9 built to pkg/valid_email2-7.0.9.gem.
Tagged v7.0.9.
Untagging v7.0.9 due to error.
rake aborted!
Running `git push origin refs/tags/v7.0.9` failed with the following output:
To https://github.com/micke/valid_email2
 ! [rejected]        v7.0.9 -> v7.0.9 (already exists)
error: failed to push some refs to 'https://github.com/micke/valid_email2'
hint: Updates were rejected because the tag already exists in the remote.
/home/runner/work/valid_email2/valid_email2/vendor/bundle/ruby/3.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `<main>'
Tasks: TOP => release => release:source_control_push
```

https://github.com/micke/valid_email2/actions/runs/13336497284/job/37252805029

the tag does not exist prior to the run. so the task actually creates it: https://github.com/micke/valid_email2/tags

**Comment by deivid-rodriguez** [comment]
No worries.

That's very strange! A potential explanation is that this googleapis/release-please-action is creating the GitHub release and creating the remote tag. Then the `rake release` task also creates and pushes the tag, and that fails because the remote tag is already there.

I think we can fix that and make the `rake release` task more resilient by checking if a _remote tag_ already exists here:

https://github.com/rubygems/rubygems/blob/c56ebfd3b3d73d6c318597d62ca928678525096f/bundler/lib/bundler/gem_helper.rb#L160-L164

(I think that method currently checks whether there's already a local tag, but not whether there's already a remote tag)

**Comment by phoet** [comment]
Sounds good to me 👍

**Comment by phoet** [comment]
@deivid-rodriguez is that something that I should patch, or will you be handling it? asking bc it looks like this is still a problem https://github.com/micke/valid_email2/actions/runs/13528647650/job/37805337604

**Comment by deivid-rodriguez** [comment]
If you can patch it that'd be great, otherwise could you please open a separate ticket explaining the issue and what needs to be done?
